[DDIDO-507]: Add redis timeout.
dpc-sdp/bay pull request #16
Opened 2020-09-09 05:21 UTC by steveworley

- Adds a timeout on the reddis connection.

2020-09-10 00:32 UTC, kurtfoster approved these changes

2020-09-10 22:58 UTC, nicksantamaria requested changes

2020-09-10 22:58 UTC, nicksantamaria commented on tests/goss.php.yaml
> -  php -r "phpinfo();":
Can we get this restored please?

2020-10-02 00:13 UTC, nicksantamaria approved these changes

2020-10-02 00:14 UTC, merged