[DDS-1576] Updated ci runner
dpc-sdp/bay pull request #194
Opened 2023-07-30 23:43 UTC by GROwen

# Checklist
- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [ ] Changelog entry has been written

Explain the **details** for making this change. What existing problem does the pull request solve?

# Changelog Entry

# Closing issues
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2023-07-31 03:49 UTC, GROwen commented on .github/workflows/build-deploy.yml
> +    - cron: '23 20 * * 0'
Schedules only run on the default branch. `5.x` in this instance.

2023-07-31 03:51 UTC, GROwen commented on .github/workflows/build-deploy.yml
> +  workflow_dispatch:
This event allows for workflows to be triggered [manually via the GitHub UI](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/). The UI feature is only visible if the workflow file is on the default branch, so we won't see it until this PR is merged.

2023-07-31 03:51 UTC, GROwen commented on .github/workflows/build-deploy.yml
> +      - uses: actions/checkout@v3
Necessary to make the bake file available to a subsequent action.

2023-08-16 01:45 UTC, nicksantamaria requested changes
@GROwen Can we get a new section in README with steps on adding new images? I spent a bit of time figuring out how the matrix works, and it depends on an [actions variable](https://github.com/dpc-sdp/bay/settings/variables/actions/IMAGES) which isn't obvious from the outset.

2023-08-21 02:11 UTC, nicksantamaria approved these changes

2023-10-03 04:59 UTC, merged