Reverted dockerize version.
dpc-sdp/bay pull request #293
Opened 2024-09-02 08:10 UTC by GROwen

Reverts the version of dockerize to the latest [dpc-sdp release](https://github.com/dpc-sdp/dockerize/releases/tag/v0.6.1)

Although looking at the [commit history](https://github.com/dpc-sdp/dockerize/commits/master/) I'm not sure why we're using a fork

2024-09-02 08:12 UTC, GROwen commented
@nicksantamaria Is there any reason you know of to not move to the [upstream version of dockerize](https://github.com/jwilder/dockerize)?

2024-09-02 23:22 UTC, nicksantamaria requested changes
@GROwen Im fairly certain the project was basically abandoned for a long while. Our fork was a fork of another fork iirc.

Looks iike there is [some activity on the project now](https://github.com/jwilder/dockerize/graphs/code-frequency). We should use the upstream and use the latest version.

2024-09-03 00:15 UTC, nicksantamaria approved these changes

2024-09-03 00:15 UTC, nicksantamaria commented
Lets kill that forked repo too

2024-09-03 00:22 UTC, merged